# Generated by Django 3.0.5 on 2020-06-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="active", field=models.BooleanField(default=True),
        ),
    ]
