# Generated by Django 3.0.5 on 2020-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200610_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
