# Generated by Django 3.0.5 on 2020-06-10 16:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200610_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
