# Generated by Django 3.0.5 on 2020-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200610_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board", name="layout", field=models.TextField(),
        ),
    ]
