# Generated by Django 3.0.5 on 2020-06-10 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20200610_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="elo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Elo"
            ),
        ),
    ]
