# Generated by Django 3.0.5 on 2020-06-10 17:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_game_uuid"),
    ]

    operations = [
        migrations.RemoveField(model_name="game", name="id",),
        migrations.AlterField(
            model_name="game",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
