# Generated by Django 3.0.5 on 2020-06-11 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0009_auto_20200611_0905"),
    ]

    operations = [
        migrations.RemoveField(model_name="player", name="elo",),
        migrations.AddField(
            model_name="elo",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
