# Generated by Django 3.0.5 on 2020-06-11 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200611_1027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elo",
            name="player",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.Player"
            ),
        ),
    ]
