# Generated by Django 3.0.5 on 2020-06-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200611_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='layout',
            new_name='fen',
        ),
    ]
