# Generated by Django 3.0.5 on 2020-06-11 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200611_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='game_uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
