# Generated by Django 3.0.5 on 2020-06-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_board_game_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="board",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.Board"
            ),
        ),
    ]
