# Generated by Django 3.0.5 on 2020-06-15 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20200614_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="result",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.Result"
            ),
        ),
    ]
