# Generated by Django 3.0.7 on 2020-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200618_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='castling_rights',
            field=models.TextField(null=True),
        ),
    ]
