# Generated by Django 3.0.7 on 2020-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200618_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='ep_square',
            field=models.IntegerField(null=True),
        ),
    ]
