# Generated by Django 3.0.7 on 2020-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_auto_20200618_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="castling_rights",
            field=models.IntegerField(null=True),
        ),
    ]
