# Generated by Django 3.0.7 on 2020-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200618_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='turn',
            field=models.BooleanField(default=True),
        ),
    ]
