# Generated by Django 3.0.7 on 2020-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_auto_20200618_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="board_fen",
            field=models.TextField(
                default="rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR"
            ),
        ),
    ]
