# Generated by Django 3.0.7 on 2020-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200625_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_fen_flipped',
            field=models.TextField(default='RNBQKBNR/PPPPPPPP/8/8/8/8/pppppppp/rnbqkbnr'),
        ),
    ]
