# Generated by Django 3.0.7 on 2020-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_board_board_fen_flipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_fen_flipped",
            field=models.TextField(
                default="RNBKQBNR/PPPPPPPP/8/8/8/8/pppppppp/rnbkqbnr"
            ),
        ),
    ]
