# Generated by Django 3.0.7 on 2020-07-16 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0035_auto_20200715_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elo',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo', to=settings.AUTH_USER_MODEL),
        ),
    ]
