# Generated by Django 3.0.7 on 2020-07-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_auto_20200716_1115"),
    ]

    operations = [
        migrations.RemoveField(model_name="elo", name="k_factor",),
    ]
