# Generated by Django 3.0.7 on 2020-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_elo_k_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='previous_rating',
            field=models.IntegerField(default=1200),
        ),
    ]
