# Generated by Django 3.0.7 on 2020-07-17 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_elo_previous_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='elo',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
